### ISSUE TITLE
Error while running command

### ISSUE THREAD

**Issue by musafarouk** [ronaldjadams/delete-tweets#1]
```bash
Traceback (most recent call last):
  File "deletetweets.py", line 92, in <module>
    main()
  File "deletetweets.py", line 87, in main
    access_token_secret=ACCESS_TOKEN_SECRET)
  File "/Users/air/Library/Python/2.7/lib/python/site-packages/twitter/api.py", line 231, in __init__
    self.SetCache(cache)
  File "/Users/air/Library/Python/2.7/lib/python/site-packages/twitter/api.py", line 4694, in SetCache
    self._cache = _FileCache()
  File "/Users/air/Library/Python/2.7/lib/python/site-packages/twitter/_file_cache.py", line 17, in __init__
    self._InitializeRootDirectory(root_directory)
  File "/Users/air/Library/Python/2.7/lib/python/site-packages/twitter/_file_cache.py", line 78, in _InitializeRootDirectory
    root_directory = self._GetTmpCachePath()
  File "/Users/air/Library/Python/2.7/lib/python/site-packages/twitter/_file_cache.py", line 74, in _GetTmpCachePath
    return os.path.join(tempfile.gettempdir(), cache_directory)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 269, in gettempdir
    tempdir = _get_default_tempdir()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 212, in _get_default_tempdir
    ("No usable temporary directory found in %s" % dirlist))
IOError: [Errno 2] No usable temporary directory found in ['/var/folders/80/4zm7_n3d04d7_9x60yk5s08w0000gp/T/', '/tmp', '/var/tmp', '/usr/tmp', '/Users/air/Documents/Python/delete-tweets']
```

I keep getting that error each time i run:

```bash
python deletetweets.py -d "2012-01-01" -r "retweet"
```

**Comment by 0xadada** [comment]
@musafarouk  are you on windows? do you have a directory named `/var/folders/80/4zm7_n3d04d7_9x60yk5s08w0000gp/T/`?

**Comment by musafarouk** [comment]
I am running on Mac
